#!/usr/bin/env sh

mkdir -pv lib
ln -sv ../usr/bin/cpp lib
ln -s gcc usr/bin/cc

install -v -dm755 usr/lib/bfd-plugins
ln -sfv ../../../usr/libexec/gcc/$(gcc -dumpmachine)/9.1.0/liblto_plugin.so \
            usr/lib/bfd-plugins/

